### ISSUE TITLE
pokemon_spec.rb

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/pokemon-scraper#7] opened 2015-12-03 23:50 UTC
The test on line 11 in pokemon_spec.rb reads : 

```
let(:pokemon) {Pokemon.new(1, "Pikachu", "fire", @db)}

  describe ".initialize" do
    it 'is initialized with a name, type and db' do
      expect(pokemon).to respond_to(:name)
      expect(pokemon).to respond_to(:type)
      expect(pokemon).to respond_to(:db)
    end
  end
```

You can see Pokemon.new takes 4 arguments, but the test only talks about, and tests three ("Pikachu", "fire", @db). The number is unexpected at this stage. 

Solutions: 
1. Mention it in the lab, and test it.
2. Create new instance of Pokemon in later test that uses it.

**Comment by victhevenot** [comment] 2016-03-01 18:31
dupe of issue #8 - closing

**Closed as completed by victhevenot** 2016-03-01 18:31 UTC
